### ISSUE TITLE
BSEC for multiple sensors?

### ISSUE THREAD

**Issue by SWaPro** [BoschSensortec/BME680_driver#10]
I'm thinking about connecting a number of BME680 sensors to one ARM processor.
Is BSEC supporting multiple sensors being used simultaneously?

**Comment by BoschSensortec** [comment]
@SWaPro ,

This is included in a special release. You will have to fill in the [contact form](https://www.bosch-sensortec.com/bst/contact/contact_form/contact_form) an request for the same.
