### ISSUE TITLE
Spi Page Datasheet Question

### ISSUE THREAD

**Issue by wjd14** [BoschSensortec/BME680_driver#2]
Hello Bosch,

Not sure if this is the right place to put this, but I figured I'd mention it. In the datasheet [here](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME680-DS001-00.pdf), it says on page 26, section 5.3.1.4 that SPI page 0 is registers 0x00 to 0x7f, and page 1 is registers 0x7f to 0xff. This seems to contradict the chart on page 24 of the datasheet. Thoughts?

**Comment by wjd14** [comment]
The datasheet was found on [this](https://www.bosch-sensortec.com/bst/products/all_products/bme680) webpage if that is useful.

**Comment by BoschSensortec** [comment]
@wjd14 ,

Thank you for pointing that out. Page 24 is correct. The description of page 0 is incorrect in section 5.3.1.4. 
The code on the other hand also marks PAGE_0 and PAGE_1 incorrectly, although it is swapped at the point of use and hence functions as expected.

In short

| Page | Addresses | spi_mem_page<4> |
|:------:|:---------:|:--------:| 
| 0 | 0x80 - 0xff | 0(default) |
| 1 | 0x00 - 0x7f | 1 |

**Comment by wjd14** [comment]
Thanks for the clarification. I was pretty sure I had it right, but I just wanted to confirm with you. Is there a better place to report little datasheet things like this? Are github issues fine, or is there another way? Thanks.

**Comment by BoschSensortec** [comment]
@wjd14 ,

Ideally issues are reported via the [contact form](https://www.bosch-sensortec.com/bst/contact/contact_form/contact_form). For all code related issues, it would be recommended to use the Github issue tracker.

**Comment by wjd14** [comment]
Thanks.
