### ISSUE TITLE
humidity calibration, register offsets mismatch?

### ISSUE THREAD

**Issue by pmeerw** [BoschSensortec/BME680_driver#24]
this doesn't look right...

#define BME680_H2_LSB_REG	(26)
#define BME680_H1_LSB_REG	(26)

**Comment by agamagtdM10102148** [comment]
What's the final answer please?

**Comment by BoschSensortec** [comment]
@agamagtdM10102148,

It is correct.  Refer https://github.com/BoschSensortec/BME680_driver/issues/1
