### ISSUE TITLE
BSEC "bsec_iot_once" as addition for "bsec_iot_loop" on arduino ?

### ISSUE THREAD

**Issue by janzieg** [BoschSensortec/BME680_driver#33]
Hi there,

the interface of bsec integration is quite limited. There is an init- and loop function and when in use, the arduino loop function becomes useless as the bsec while-loop blocks processing.

It would be nice to also have something like "bsec_iot_once" for single time measurements that could be used with the arduino main loop function (and so with other operations).

(i added my own function to bsec_integration right now for this as a copy from bsec_iot_loop but without while-loop and changed state saving behavior).

What do you think about it ?

**Comment by BoschSensortec** [comment]
Hi @janzieg,

We will be releasing a Arduino friendly library based on the existing BSEC library shortly.

**Comment by janzieg** [comment]
@BoschSensortec Thx, looking forward to it...

**Comment by jttaylor86** [comment]
Hello, when is the Arduino library coming?

**Comment by r0ehre** [comment]
Really looking forward to the release of the BSEC library for Arduino!

**Comment by janzieg** [comment]
@BoschSensortec Thx, this works for me - I can now use it properly within the arduino loop function.

New library, new question, https://github.com/BoschSensortec/BSEC-Arduino-library/issues/5 :)
