### ISSUE TITLE
Integer pressure calculation lacks precision

### ISSUE THREAD

**Issue by ourairquality** [BoschSensortec/BME680_driver#44]
The 32 bit integer function `calc_pressure()` is rather inaccurate and an error of 5 Pa is not uncommon. Surely an integer version could do better, even if it had to use 64 bit integer operations in some places.

The most significant problem seems to be the limited precision of `var1` in the division at:
```pressure_comp = ((pressure_comp << 1) / (uint32_t)var1);```

Would a patch be accepted that used 64 bit integer operations where necessary to reduce the error?

**Comment by BoschSensortec** [comment]
Hi @ourairquality,

Are you referring to this [line of code](https://github.com/BoschSensortec/BME680_driver/blob/b619094dfe507034e1034884f4638a78dae7646c/bme680.c#L918) specifically? Or are you referring to the whole API of `calc_pressure`.

We currently do not accept patches, but we do solve issues if reported and release it on Github.

**Comment by BoschSensortec** [comment]
Hi @ourairquality,

Thank you for your feedback. We will look into this and update it as per your suggestions.
