### ISSUE TITLE
BME680_E_COM_FAIL error unexpectedly

### ISSUE THREAD

**Issue by sysizlayan** [BoschSensortec/BME680_driver#56]
Hi,
I am using BME680 with BSEC library on ESP32.
The sensor works around 30-60 minutes without any problem but after some point the program begins to give BME680_E_COM_FAIL errors. There is no problem with physical connections. The program resets the MCU after that but BME680 error remains the same as -2 (BME_E_COM_FAIL).
What the reason for that? Is there a method to prevent that or is there a recover method?

Thanks in advance.

**Comment by BoschSensortec** [comment]
Hi @sysizlayan,

The error is `BME680_E_COM_FAIL` indicates that the Wire or SPI library calls returned an error code.

**Comment by sysizlayan** [comment]
You mean Wire or SPI classes?

**Comment by BoschSensortec** [comment]
@sysizlayan,

Yes.

**Comment by sysizlayan** [comment]
Thanks.
