### ISSUE TITLE
Selftest: Minimum humidity limit too high?

### ISSUE THREAD

**Issue by ojousima** [BoschSensortec/BME680_driver#84]
The self-test of BME680 relies on actual indoor humidity being over 20% RH. While this is a valid assumption most of the time, for example right now the temperature is a bit below -20C in Helsinki, Finland. This leads to dry indoor air (18 % in my case) which in turn causes self-test to fail.

**Comment by BoschSensortec** [comment]
Hi @ojousima,

Yes, you are right. The self-test snippet is a reference for the end-of-line production test of the devices using the BME680. Our existing customers run this indoors at room temperature. You would have to modify the self-test to suit your test environment.

**Comment by ojousima** [comment]
Thanks,

Just to clarify, we're also running this indoors at room temperature. However the outdoor conditions (extremely dry air) are reflected to indoors. 

I'll adjust the test on our end and close this issue.
